name: Update Manifest and Commit Changes
on:
  push:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Update Manifest and Commit Changes
        uses: ubiquity-os/action-deploy-plugin@main
        with:
          manifestPath: ${{ github.workspace }}/manifest.json
          schemaPath: ${{ github.workspace }}/src/types/plugin-input.js
          pluginEntry: ${{ github.workspace }}/src/plugin.ts
          commitMessage: "chore: updated manifest.json and dist build"
          nodeVersion: "20.10.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}